-- CreateTable
CREATE TABLE "bulk_analysis_results" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "match_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "home_team" TEXT NOT NULL,
    "away_team" TEXT NOT NULL,
    "league_name" TEXT NOT NULL,
    "match_time" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "predicted_winner" TEXT,
    "winner_confidence" REAL,
    "btts_prediction" TEXT,
    "btts_confidence" REAL,
    "over_under_prediction" TEXT,
    "over_under_confidence" REAL,
    "home_form_score" REAL,
    "away_form_score" REAL,
    "head_to_head_score" REAL,
    "home_advantage" REAL,
    "goals_analysis" REAL,
    "overall_confidence" REAL,
    "confidence_tier" TEXT,
    "recommendation" TEXT,
    "risk_level" TEXT,
    "expected_value" REAL,
    "kelly_percentage" REAL,
    "api_ms_home_shots_on_goal" INTEGER,
    "api_ms_home_shots_off_goal" INTEGER,
    "api_ms_home_total_shots" INTEGER,
    "api_ms_home_ball_possession" TEXT,
    "api_ms_home_yellow_cards" INTEGER,
    "api_ms_home_red_cards" INTEGER,
    "api_ms_home_corner_kicks" INTEGER,
    "api_ms_home_fouls" INTEGER,
    "api_ms_away_shots_on_goal" INTEGER,
    "api_ms_away_shots_off_goal" INTEGER,
    "api_ms_away_total_shots" INTEGER,
    "api_ms_away_ball_possession" TEXT,
    "api_ms_away_yellow_cards" INTEGER,
    "api_ms_away_red_cards" INTEGER,
    "api_ms_away_corner_kicks" INTEGER,
    "api_ms_away_fouls" INTEGER,
    "api_form_home_last_5" TEXT,
    "api_form_home_wins_last_5" INTEGER,
    "api_form_home_losses_last_5" INTEGER,
    "api_form_away_last_5" TEXT,
    "api_form_away_wins_last_5" INTEGER,
    "api_form_away_losses_last_5" INTEGER,
    "api_h2h_total_matches" INTEGER,
    "api_h2h_home_wins" INTEGER,
    "api_h2h_away_wins" INTEGER,
    "api_h2h_draws" INTEGER,
    "api_h2h_avg_goals_per_match" REAL,
    "api_league_home_position" INTEGER,
    "api_league_away_position" INTEGER,
    "api_league_home_points" INTEGER,
    "api_league_away_points" INTEGER,
    "api_league_avg_goals_home" REAL,
    "api_league_avg_goals_away" REAL,
    "own_an_value_score" REAL,
    "own_an_momentum_score" REAL,
    "own_an_injury_impact" REAL,
    "own_an_weather_impact" REAL,
    "own_an_referee_tendency" REAL,
    "own_an_crowd_factor" REAL,
    "risk_variance_score" REAL,
    "risk_liquidity_score" REAL,
    "risk_odds_movement" REAL,
    "risk_last_minute_changes" REAL,
    "perf_historical_accuracy" REAL,
    "perf_recent_form_weight" REAL,
    "perf_league_specific_adj" REAL,
    "perf_algorithm_confidence" REAL,
    "market_odds_home" REAL,
    "market_odds_away" REAL,
    "market_odds_draw" REAL,
    "market_volume_indicator" REAL,
    "market_smart_money_flow" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE INDEX "bulk_analysis_results_date_confidence_tier_idx" ON "bulk_analysis_results"("date", "confidence_tier");

-- CreateIndex
CREATE INDEX "bulk_analysis_results_league_name_overall_confidence_idx" ON "bulk_analysis_results"("league_name", "overall_confidence");

-- CreateIndex
CREATE INDEX "bulk_analysis_results_api_league_home_position_api_league_away_position_idx" ON "bulk_analysis_results"("api_league_home_position", "api_league_away_position");

-- CreateIndex
CREATE INDEX "bulk_analysis_results_own_an_value_score_risk_variance_score_idx" ON "bulk_analysis_results"("own_an_value_score", "risk_variance_score");
