import type { SportConfig } from '../_core/types';

export const footballConfig: SportConfig = {
  id: 'football',
  displayName: 'Football',
  displayNameTR: 'Futbol',
  apiBase: 'https://v3.football.api-sports.io',
  apiKey: 'b9ccb3be380b9f990745280ac95b4763',
  avgScoreHome: 1.50,
  avgScoreAway: 1.10,
  homeAdvantage: 1.10,
  scoreMethod: 'poisson',
  allowsDraw: true,
  iddaaCategory: 'FB',
  availableMarkets: [
    'Match Winner',
    'Home/Away',
    'Second Half Winner',
    'First Half Winner',
    'Goals Over/Under',
    'Goals Over/Under First Half',
    'Goals Over/Under - Second Half',
    'Both Teams Score',
    'Both Teams To Score - First Half',
    'Both Teams To Score - Second Half',
    'Exact Score',
    'Double Chance',
    'First Half Double Chance',
    'Handicap Result',
    'Asian Handicap',
    'HT/FT Double',
    'Total - Home',
    'Total - Away',
    'Team To Score First',
    'Team To Score Last',
    'Exact Goals Number',
    'Odd/Even',
    'Home Odd/Even',
    'Results/Total Goals',
    'Winning Margin',
    'Corners Over Under',
    'Cards Over/Under',
  ],
  marketNameMapping: {
    'Match Winner': 'Maç Sonucu',
    'Home/Away': 'Beraberlik Yok (Çifte Şans Olmadan)',
    'Goals Over/Under': 'Alt/Üst',
    'Both Teams Score': 'Karşılıklı Gol (KG Var/Yok)',
    'Double Chance': 'Çifte Şans',
    'Exact Score': 'Skor Tahmini',
    'Asian Handicap': 'Handikaplı Maç Sonucu',
    'Handicap Result': 'Handikap',
    'HT/FT Double': 'İlk Yarı / Maç Sonucu',
    'First Half Winner': 'İlk Yarı Sonucu',
    'Total - Home': 'Ev Sahibi Toplam Gol',
    'Total - Away': 'Deplasman Toplam Gol',
    'Odd/Even': 'Tek/Çift',
    'Corners Over Under': 'Korner Alt/Üst',
    'Cards Over/Under': 'Kart Alt/Üst',
    'Both Teams To Score - First Half': 'KG İlk Yarı',
    'Exact Goals Number': 'Toplam Gol Sayısı',
    'Winning Margin': 'Kazanma Farkı',
  },
};
