import { Prisma, PrismaClient } from '@prisma/client';

import type { PredictionMetadata, SourceSnapshots } from '@/lib/types';
import type { EnsemblePrediction } from '@/lib/types/ensemble-types';

// Teach JSON.stringify to handle BigInt — Prisma PostgreSQL returns BigInt
// for SERIAL/bigint columns (e.g. picks.id, system_bets.id), which the
// default NextResponse.json() cannot serialize. Cast to Number (safe for
// autoincrement ids up to 2^53) via toJSON hook.
if (typeof (BigInt.prototype as any).toJSON !== 'function') {
  (BigInt.prototype as any).toJSON = function (this: bigint) {
    const n = Number(this);
    return Number.isSafeInteger(n) ? n : this.toString();
  };
}

// Lazy-require the separate tracking Prisma client (PostgreSQL).
// Generated by `npx prisma generate --schema=prisma-tracking/schema.prisma`
// at build time. Kept optional so the legacy build still works even when
// the tracking client hasn't been regenerated yet.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const TrackingClientModule: any = (() => {
  try { return require('.prisma/tracking-client'); } catch { return null; }
})();

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
  trackingPrisma: any;
};

// Prisma schema uses SQLite. If no DATABASE_URL is provided (e.g. in scripts
// that forget to load .env), fall back to the project-local dev.db file so
// we never create a nested `prisma/prisma/dev.db` like earlier revisions.
if (!process.env.DATABASE_URL) {
  process.env.DATABASE_URL = 'file:./prisma/dev.db';
}

export const prisma = globalForPrisma.prisma ??
  new PrismaClient({
    log: ['error', 'warn'],
  });

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}

interface SaveEnsemblePredictionParams {
  matchId: number;
  ensemblePrediction: EnsemblePrediction;
  metadata?: PredictionMetadata;
  sourceSnapshots?: SourceSnapshots;
}

const clamp = (value: number | null | undefined, min = 0, max = 1): number => {
  if (typeof value !== 'number' || Number.isNaN(value)) {
    return min;
  }
  return Math.max(min, Math.min(max, value));
};

const ratioOrNull = (numerator?: number | null, denominator?: number | null): number | null => {
  if (!numerator || !denominator || denominator === 0) {
    return null;
  }
  return numerator / denominator;
};

export async function saveEnsemblePrediction({
  matchId,
  ensemblePrediction,
  metadata,
  sourceSnapshots,
}: SaveEnsemblePredictionParams): Promise<void> {
  try {
    const predictedValue = ensemblePrediction.matchResult.prediction;
    const overallConfidence = clamp(ensemblePrediction.confidence.overall.value, 0, 1);

    const factorsPayload = {
      confidence: ensemblePrediction.confidence,
      bankoSelections: ensemblePrediction.bankoSelections,
      diagnostics: ensemblePrediction.diagnostics,
      sourceSnapshots,
    };

    const homeFormScore = metadata?.homeForm?.form_score ?? null;
    const awayFormScore = metadata?.awayForm?.form_score ?? null;
    const headToHeadScore = metadata?.h2hRecord
      ? ratioOrNull(metadata.h2hRecord.team1_wins, metadata.h2hRecord.total_matches)
      : null;
    const homeAdvantageScore = metadata?.h2hRecord
      ? clamp(
          (metadata.h2hRecord.team1_wins - metadata.h2hRecord.team2_wins) /
            (metadata.h2hRecord.total_matches || 1) /
            2 +
            0.5,
          0,
          1
        )
      : null;
    const goalsAnalysisScore = typeof ensemblePrediction.goals.expectedTotalGoals === 'number'
      ? ensemblePrediction.goals.expectedTotalGoals
      : null;

    const existingPrediction = await prisma.prediction.findFirst({
      where: {
        match_id: matchId,
        prediction_type: 'ensemble',
        algorithm_version: '3.0',
      },
    });

    const factorsUsed = factorsPayload as unknown as Prisma.InputJsonValue;
    const basePayload = {
      prediction_type: 'ensemble',
      predicted_value: predictedValue,
      confidence_score: overallConfidence,
      home_form_score: homeFormScore,
      away_form_score: awayFormScore,
      head_to_head_score: headToHeadScore,
      home_advantage_score: homeAdvantageScore,
      goals_analysis_score: goalsAnalysisScore,
      factors_used: factorsUsed,
      algorithm_version: '3.0',
      is_high_confidence: overallConfidence >= 0.7,
    };

    if (existingPrediction) {
      await prisma.prediction.update({
        where: { id: existingPrediction.id },
        data: basePayload as Prisma.PredictionUncheckedUpdateInput,
      });
    } else {
      await prisma.prediction.create({
        data: {
          match_id: matchId,
          ...basePayload,
        } as Prisma.PredictionUncheckedCreateInput,
      });
    }

    // DUAL-WRITE HOOK: mirror to tracking DB (non-fatal, additive)
    // Imported lazily to avoid a circular dep between lib/db and
    // lib/tracking/dual-write-hook (which itself imports from lib/db).
    try {
      const { mirrorToTracking } = await import('@/lib/tracking/dual-write-hook');
      const homeWinProb = clamp(ensemblePrediction.matchResult.probabilities.home, 0, 1);
      const drawProb = clamp(ensemblePrediction.matchResult.probabilities.draw, 0, 1);
      const awayWinProb = clamp(ensemblePrediction.matchResult.probabilities.away, 0, 1);
      const bestIsHome = predictedValue === 'home';
      const bestIsAway = predictedValue === 'away';
      const bestMarket = bestIsHome ? 'HOME_WIN' : bestIsAway ? 'AWAY_WIN' : 'DRAW';
      const bestLabel = bestIsHome ? 'MS 1' : bestIsAway ? 'MS 2' : 'MS X';
      const bestProb = bestIsHome ? homeWinProb : bestIsAway ? awayWinProb : drawProb;
      const picks = [
        {
          market: 'HOME_WIN',
          market_label: 'MS 1',
          pick_label: 'Ev sahibi kazanır',
          category: 'MAÇ_SONUCU',
          probability: homeWinProb,
          is_best: bestMarket === 'HOME_WIN',
        },
        {
          market: 'DRAW',
          market_label: 'MS X',
          pick_label: 'Beraberlik',
          category: 'MAÇ_SONUCU',
          probability: drawProb,
          is_best: bestMarket === 'DRAW',
        },
        {
          market: 'AWAY_WIN',
          market_label: 'MS 2',
          pick_label: 'Deplasman kazanır',
          category: 'MAÇ_SONUCU',
          probability: awayWinProb,
          is_best: bestMarket === 'AWAY_WIN',
        },
      ];
      // Match metadata not carried by PredictionMetadata — query it cheaply
      // from the SQLite `matches` table we just wrote to. If missing, we still
      // mirror with placeholder team/league strings.
      const matchRow = await prisma.match.findUnique({
        where: { id: matchId },
        select: {
          date: true,
          homeTeam: { select: { name: true } },
          awayTeam: { select: { name: true } },
          league: { select: { name: true } },
        },
      });
      await mirrorToTracking({
        sport: 'football',
        fixture_id: matchId,
        home_team: matchRow?.homeTeam?.name ?? `team-${matchId}-home`,
        away_team: matchRow?.awayTeam?.name ?? `team-${matchId}-away`,
        league: matchRow?.league?.name,
        match_date: matchRow?.date ?? new Date(),
        home_win_prob: homeWinProb,
        draw_prob: drawProb,
        away_win_prob: awayWinProb,
        confidence: overallConfidence,
        best_market: bestMarket,
        best_pick_label: bestLabel,
        best_probability: bestProb,
        picks,
        payload: {
          engine: 'ensemble',
          algorithm_version: '3.0',
          predicted_value: predictedValue,
        },
      });
    } catch (mirrorErr) {
      // Never throw from the tracking mirror path. Log and continue.
      console.warn(
        '[tracking] saveEnsemblePrediction mirror skipped:',
        mirrorErr instanceof Error ? mirrorErr.message : mirrorErr
      );
    }
  } catch (error) {
    console.error('[PREDICTION] Failed to persist ensemble prediction:', error);
  }
}

// Gracefully handle connection
prisma.$connect().catch((error: unknown) => {
  console.error('Failed to connect to database:', error);
});

// ---------------------------------------------------------------------------
// Tracking Prisma client (PostgreSQL probet DB, separate from SQLite).
// Populated by lib/tracking/* + /api/tracking/*. Never touches the legacy
// SQLite store the user's engines rely on.
// ---------------------------------------------------------------------------

let trackingInstance: any = globalForPrisma.trackingPrisma ?? null;
if (!trackingInstance && TrackingClientModule?.PrismaClient) {
  try {
    trackingInstance = new TrackingClientModule.PrismaClient({ log: ['error', 'warn'] });
    if (process.env.NODE_ENV !== 'production') {
      globalForPrisma.trackingPrisma = trackingInstance;
    }
  } catch (err) {
    console.warn('[db] tracking client init failed:', err instanceof Error ? err.message : err);
  }
}
export const trackingPrisma: any = trackingInstance;

export function isTrackingEnabled(): boolean {
  return trackingPrisma !== null && !!process.env.TRACKING_DATABASE_URL;
}

if (trackingPrisma && process.env.TRACKING_DATABASE_URL) {
  trackingPrisma.$connect().catch((error: unknown) => {
    console.warn('[db] tracking connect failed:', error instanceof Error ? error.message : error);
  });
}
